version = 0.1

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "staging-todo-list-aws"
#s3_bucket = "aws-sam-cli-managed-staging-samclisourcebucket-upt09go84tay"
s3_prefix = "staging-todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
image_repositories = []
resolve_s3 = true

[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "production-todo-list-aws"
#s3_bucket = "aws-sam-cli-managed-production-samclisourcebucket-upt09go84tay"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"production\""
image_repositories = []
resolve_s3 = true
